# Generated by Django 4.2.7 on 2025-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='numero',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
